Add workflow template
SnowSoftwareGlobal/.github pull request #25
Opened 2024-07-09 19:43 UTC by dancundy

2024-07-09 20:11 UTC, bdoughan-snow commented on workflow-templates/openapi-generation-validation.properties.json
> +  "description": "Workflow that will automate the generation of your open api specification and then provide validation comments as part of the same pull request. This workflow will also generate a m
```suggestion
  "description": "Workflow that will automate the generation of your OpenAPI specification and then provide validation comments as part of the same pull request. This workflow will also generate a markdown file which allows for easy viewing of OpenAPI specification from within GitHub.",
```

2024-07-09 20:12 UTC, bdoughan-snow commented on workflow-templates/openapi-generation-validation.properties.json
> +  "iconName": "octicon checklist",
Here is a list of octicons if you want to choose something different:
https://primer.style/foundations/icons

2024-07-09 20:14 UTC, bdoughan-snow commented on workflow-templates/openapi-generation-validation.yaml
> +    secrets: inherit # pass all secrets (https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow)
It may be better to leave these out, and have teams use the OpenAPI Validation workflow instead.

2024-07-09 20:14 UTC, bdoughan-snow requested changes
See inline comments.

2024-07-09 20:53 UTC, dancundy commented on workflow-templates/openapi-generation-validation.properties.json
> +  "iconName": "octicon checklist",
I had a quick peek but I think the checklist one you chose looks pretty relevant, so decided to stick with it.

2024-07-09 20:55 UTC, dancundy commented on workflow-templates/openapi-generation-validation.yaml
> +    secrets: inherit # pass all secrets (https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow)
The problem with doing that is that you then cannot have them dependent on each other, Currently with this workflow, the validation and markdown won't start until generation has finished.

2024-07-11 14:03 UTC, bdoughan-snow commented on workflow-templates/openapi-generation-validation.yaml
> +    uses: SnowSoftwareGlobal/api-guidelines/.github/workflows/openapi-validation.yml@v1.0.3
```suggestion
    uses: SnowSoftwareGlobal/api-guidelines/.github/workflows/openapi-validation.yml@v1.0
```

2024-07-11 14:07 UTC, bdoughan-snow approved these changes

2024-07-12 09:09 UTC, ViktorLindgren95 approved these changes

2024-07-15 07:28 UTC, merged